### ISSUE TITLE
Hovering over assignment in classwork section makes it fully white.

### ISSUE THREAD

**Issue by aadishsamir123** [RyanLua/ClassroomDarkMode#95]
### Description

In the classwork section of a class, when hovering over an assignment name, the assignment container becomes fully white.

### Expected behavior

The background color should not change to white

### Actual behavior

The background color changed to white

![Bug Showcase Image](https://github.com/user-attachments/assets/6d826718-6b5a-43d9-93c6-f7409d5b7641)

### Steps to reproduce

1. Go to a Google Classroom class
2. Go to classwork section
3. Hover over any assignment

### Other details

I am using Vivaldi browser.

### Extension Version

0.1.2

### Platform

Other

### Browser Version

6.9.3447.44 (Stable channel) (arm64)

### Severity

High

### Code of Conduct

- [x] I have read and agree to the project's [Code of Conduct](https://github.com/RyanLua/ClassroomDarkMode?tab=coc-ov-file)

**Comment by RyanLua** [comment]
Thanks for reporting this. I've been to reproduce the issue and am working on a fix soon.

**Comment by aadishsamir123** [comment]
Thanks for taking the time to fix this!

**Comment by RyanLua** [comment]
It seems like the issue was solved in https://github.com/RyanLua/ClassroomDarkMode/commit/31db5921a150cebff9180a6991441c0f7df04ba1 but I haven't published a version containing the fix. I've just published [0.1.3](https://github.com/RyanLua/ClassroomDarkMode/releases/tag/0.1.3) which should contain the fix and other changes.

The new version has been submitted to addon/extension stores and needs time to get approved (up to a week usually). From the time I'm writing this, only Firefox has already approved it out of the four.

I'll close this issue now. Just wait for 0.1.3 and install it and you should be all set. If this still occurs, feel free to reopen this issue.

**Comment by aadishsamir123** [comment]
You know, this is probably the best classroom dark mode extension I've ever used, and I'm a huge fan of open-source developers as they are always so transparent and the code is viewable and the community can easily contribute to projects. I myself am an open-source dev
